#!/bin/sh

export GOPATH=`pwd`/Godeps/_workspace:$GOPATH
version=$1

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o envtmpl-linux-amd64-$version .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o envtmpl-darwin-amd64-$version .

hub release create -a envtmpl-linux-amd64-$version envtmpl-darwin-amd64-$version v$version

rm envtmpl-*
